### ISSUE TITLE
Link in README (and website tutorial) is broken

### ISSUE THREAD

**Issue by biodrone** [raspberrypilearning/octapi-setup#2]
The link to https://github.com/raspberrypilearning/rpi-python-build-an-octapi is a GitHub 404 page now. 

The same can be seen on https://projects.raspberrypi.org/en/projects/rpi-python-build-an-octapi as the link at the bottom of the page points to the same GitHub repository.

**Comment by MarcScott** [comment]
Repo has now been made public
